# Generated by Django 3.2.5 on 2021-07-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
