# Generated by Django 3.2.5 on 2021-07-23 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_postmodel_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='user',
            new_name='username',
        ),
    ]
